Repository snyk/code-client-go, pull requests merged in 2024-04, with the labels that each got.

#17 feat: add client for the workspace API [IDE-200]
  .gitignore
  CONTRIBUTING.md
  Makefile
  go.mod
  go.sum
  internal/workspace/2024-03-12/client.go
  internal/workspace/2024-03-12/client_test.go
  internal/workspace/2024-03-12/common/common.config.yaml
  internal/workspace/2024-03-12/common/common.go
  internal/workspace/2024-03-12/gen.go
  internal/workspace/2024-03-12/links/links.config.yaml
  internal/workspace/2024-03-12/links/links.go
  internal/workspace/2024-03-12/parameters/orgs.config.yaml
  internal/workspace/2024-03-12/parameters/orgs.go
  internal/workspace/2024-03-12/parameters/request-id.config.yaml
  internal/workspace/2024-03-12/parameters/request-id.go
  internal/workspace/2024-03-12/parameters/user-agent.config.yaml
  internal/workspace/2024-03-12/parameters/user-agent.go
  internal/workspace/2024-03-12/spec.config.yaml
  internal/workspace/2024-03-12/workspaces/workspaces.config.yaml
  internal/workspace/2024-03-12/workspaces/workspaces.go
  scripts/download-workspace-api.sh
  tools.go
Labels: feature

#19 fix: include code quality issues
  .circleci/config.yml
  .gitleaksignore
  internal/analysis/analysis_test.go
  internal/analysis/fake.json
Labels: fix

#25 chore: fix download script
  go.mod
  go.sum
  internal/orchestration/2024-02-16/client.go
  internal/orchestration/2024-02-16/client_test.go
  internal/orchestration/2024-02-16/common/common.go
  internal/orchestration/2024-02-16/parameters/orgs.go
  internal/orchestration/2024-02-16/parameters/scans.go
  internal/orchestration/2024-02-16/scans/scans.go
  internal/workspace/2024-03-12/client.go
  internal/workspace/2024-03-12/common/common.go
  internal/workspace/2024-03-12/gen.go
  internal/workspace/2024-03-12/links/links.go
  internal/workspace/2024-03-12/parameters/content-type.config.yaml
  internal/workspace/2024-03-12/parameters/content-type.go
  internal/workspace/2024-03-12/parameters/orgs.go
  internal/workspace/2024-03-12/parameters/request-id.go
  internal/workspace/2024-03-12/parameters/user-agent.go
  internal/workspace/2024-03-12/workspaces/workspaces.go
  scripts/download-workspace-api.py
  scripts/utils.py
Labels: ignore-for-release

#26 fix: remove usage of global logger
  internal/bundle/bundle_manager.go
  internal/deepcode/helpers.go
  scan_test.go
Labels: fix

#27 fix: repository url computation
  internal/util/repository.go
  internal/util/repository_test.go
Labels: fix

#28 fix: extract sarif document to named Struct for reuse
  sarif/sarif_types.go
Labels: fix

#29 fix: repo url subfolder [IDE-246]
  http/http.go
  http/http_test.go
  internal/analysis/analysis_test.go
  internal/deepcode/client_pact_test.go
  internal/util/repository.go
  internal/util/repository_test.go
  internal/workspace/2024-03-12/client_pact_test.go
  observability/error_reporter_impl.go
  observability/instrumentor_impl.go
  observability/noop_span.go
  observability/traceid.go
  scan_smoke_test.go
Labels: fix

#36 feat: retrieve real findings [IDE-245]
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/orchestration/2024-02-16/client_pact_test.go
  internal/orchestration/2024-02-16/pacts/code-client-go-orchestrationapi.json
  internal/workspace/2024-03-12/client_pact_test.go
  internal/workspace/2024-03-12/pacts/code-client-go-workspaceapi.json
Labels: feature

#37 fix: deal with real sarif response
  .gitleaksignore
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/analysis/fake.json
  sarif/sarif_types.go
  scan_smoke_test.go
Labels: fix

#39 fix: remove println
  internal/analysis/analysis.go
Labels: fix

#41 fix: logging for retrieving SARIF
  internal/analysis/analysis.go
Labels: fix
