Repository snyk/code-client-go, pull requests merged in 2024-05, with the labels that each got.

#42 chore: Introduce Option to specify repository URL
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/analysis/mocks/analysis.go
  internal/orchestration/2024-02-16/pacts/code-client-go-orchestrationapi.json
  internal/util/repository.go
  scan.go
  scan/target.go
  scan/target_test.go
  scan_smoke_test.go
  scan_test.go
Labels: ignore-for-release

#43 fix: logging improvements
  http/http.go
  internal/analysis/analysis.go
  internal/deepcode/client.go
  scan.go
Labels: fix

#44 fix: Fix missing interface change
  scan.go
Labels: fix

#34 chore: improve local dev and ci/cd
  .circleci/config.yml
  .github/pull_request_template.md
  .github/workflows/release.yml
  CONTRIBUTING.md
  Makefile
  internal/bundle/bundle_manager_test.go
  internal/bundle/bundle_test.go
  internal/deepcode/client_pact_test.go
  internal/deepcode/mocks/client.go
  internal/orchestration/2024-02-16/client_pact_test.go
  internal/orchestration/2024-02-16/common/common.go
  internal/orchestration/2024-02-16/gen.go
  internal/workspace/2024-03-12/client_pact_test.go
  internal/workspace/2024-03-12/common/common.go
  internal/workspace/2024-03-12/gen.go
  scan_smoke_test.go
  scan_test.go
  scripts/download-orchestration-api.py
  scripts/download-workspace-api.py
  scripts/utils.py
Labels: ignore-for-release

#45 fix: fall back to path when no repo URL provided
  scan/target.go
  scan/target_test.go
Labels: fix

#49 feat: progress tracker [IDE-222]
  README.md
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/analysis/mocks/analysis.go
  internal/bundle/bundle.go
  internal/bundle/bundle_manager.go
  internal/bundle/bundle_manager_test.go
  internal/bundle/bundle_test.go
  internal/bundle/mocks/bundle.go
  internal/orchestration/2024-02-16/common/common.go
  internal/orchestration/2024-02-16/pacts/code-client-go-orchestrationapi.json
  internal/workspace/2024-03-12/common/common.go
  scan.go
  scan/mocks/tracker.go
  scan/tracker.go
  scan/tracker_impl.go
  scan_smoke_test.go
  scan_test.go
Labels: feature

#50 fix: expose SarifCoverage as reusable type
  sarif/sarif_types.go
Labels: fix

#51 fix: remove v1 suffix for ApiUrl if exists [IDE-353]
  internal/analysis/analysis.go
Labels: fix
