Repository snyk/code-client-go, pull requests merged in 2024-11, with the labels that each got.

#63 chore: align with shared team ownership
  .github/CODEOWNERS
Labels: ignore-for-release

#62 feat: extend sarif schema with policy property
  sarif/sarif_types.go
Labels: feature

#64 fix: make ResultProperties.Policy nilable
  internal/analysis/analysis_test.go
  internal/analysis/fake.json
  sarif/sarif_types.go
Labels: fix
