Repository snyk/code-client-go, pull requests merged in 2025-09, with the labels that each got.

#110 chore: update to Go 1.24 [IDE-1377]
  .circleci/config.yml
  .github/workflows/release.yml
  .golangci.yaml
  Makefile
  bundle/bundle_manager_test.go
  bundle/bundle_test.go
  go.mod
  go.sum
  internal/analysis/analysis_legacy_test.go
  internal/analysis/analysis_test.go
  internal/deepcode/client_test.go
  internal/deepcode/pacts/code-client-go-snykcodeapi.json
  llm/api_client_test.go
  llm/binding_smoke_test.go
  llm/binding_test.go
  scan_test.go
Labels: ignore-for-release

#114 chore: use `go tool` [IDE-1377]
  Makefile
  bundle/bundle.go
  bundle/bundle_manager.go
  config/config.go
  go.mod
  http/http.go
  internal/analysis/analysis.go
  internal/api/test/2024-12-21/gen.go
  internal/deepcode/client.go
  observability/error_reporter.go
  observability/instrumentor.go
  scan/tracker.go
  tools.go
Labels: ignore-for-release

#113 fix: consolidate llm client logic so all requests have consistent headers [IDE-1350]
  README.md
  http/http.go
  internal/analysis/analysis_legacy.go
  internal/analysis/analysis_legacy_test.go
  internal/deepcode/client.go
  llm/api_client.go
  llm/api_client_test.go
  scan.go
  scan/resultmetadata.go
  scan/scan_metadata.go
Labels: fix

#124 feat: support test-service commitId
  .gitignore
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/api/test/2025-04-07/client.go
  internal/api/test/2025-04-07/common/common.config.yaml
  internal/api/test/2025-04-07/common/common.go
  internal/api/test/2025-04-07/common/common.yaml
  internal/api/test/2025-04-07/gen.go
  internal/api/test/2025-04-07/helper.go
  internal/api/test/2025-04-07/models/components.config.yaml
  internal/api/test/2025-04-07/models/components.go
  internal/api/test/2025-04-07/models/components.yaml
  internal/api/test/2025-04-07/models/tests.config.yaml
  internal/api/test/2025-04-07/models/tests.go
  internal/api/test/2025-04-07/models/tests.yaml
  internal/api/test/2025-04-07/parameters/orgs.config.yaml
  internal/api/test/2025-04-07/parameters/orgs.go
  internal/api/test/2025-04-07/parameters/orgs.yaml
  internal/api/test/2025-04-07/parameters/tests.config.yaml
  internal/api/test/2025-04-07/parameters/tests.go
  internal/api/test/2025-04-07/parameters/tests.yaml
  internal/api/test/2025-04-07/spec.config.yaml
  internal/api/test/2025-04-07/spec.yaml
  internal/util/repository.go
  internal/util/repository_test.go
  scan.go
  scan/target.go
  scan/target_test.go
  scripts/download-test-api.py
Labels: feature

#126 chore(tests): fix test assertion
  internal/analysis/analysis_test.go
Labels: ignore-for-release
