Repository snyk/code-client-go, pull requests merged in 2025-04, with the labels that each got.

#92 feat: add Status and Guid properties to Suppression type
  sarif/sarif_types.go
Labels: feature

#87 feat: improve bundle performance [IDE-937]
  internal/bundle/bundle.go
  internal/bundle/bundle_manager.go
  internal/bundle/bundle_manager_test.go
  internal/bundle/mocks/bundle.go
  internal/deepcode/helpers.go
  internal/util/hash.go
Labels: feature

#93 fix: revert #87
  internal/bundle/bundle.go
  internal/bundle/bundle_manager.go
  internal/bundle/bundle_manager_test.go
  internal/bundle/mocks/bundle.go
  internal/deepcode/helpers.go
  internal/util/hash.go
Labels: fix

#95 feat: add Upload function to CodeScanner interface
  scan.go
Labels: feature

#97 chore: expose Bundle interface
  bundle/bundle.go
  bundle/bundle_manager.go
  bundle/bundle_manager_test.go
  bundle/bundle_test.go
  bundle/errors.go
  bundle/mocks/bundle.go
  bundle/mocks/bundle_manager.go
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/analysis/mocks/analysis.go
  scan.go
  scan_test.go
Labels: ignore-for-release
