Repository snyk/code-client-go, pull requests merged in 2025-03, with the labels that each got.

#79 chore: cleanup obsolete code
  .circleci/config.yml
  .github/CODEOWNERS
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/analysis/mocks/analysis.go
  internal/orchestration/2024-02-16/client.go
  internal/orchestration/2024-02-16/client_pact_test.go
  internal/orchestration/2024-02-16/client_test.go
  internal/orchestration/2024-02-16/common/common.config.yaml
  internal/orchestration/2024-02-16/common/common.go
  internal/orchestration/2024-02-16/gen.go
  internal/orchestration/2024-02-16/pacts/code-client-go-orchestration-service.json
  internal/orchestration/2024-02-16/parameters/orgs.config.yaml
  internal/orchestration/2024-02-16/parameters/orgs.go
  internal/orchestration/2024-02-16/parameters/scans.config.yaml
  internal/orchestration/2024-02-16/parameters/scans.go
  internal/orchestration/2024-02-16/scans/scans.config.yaml
  internal/orchestration/2024-02-16/scans/scans.go
  internal/orchestration/2024-02-16/spec.config.yaml
  internal/workspace/2024-05-14/client.go
  internal/workspace/2024-05-14/client_pact_test.go
  internal/workspace/2024-05-14/client_test.go
  internal/workspace/2024-05-14/common/common.config.yaml
  internal/workspace/2024-05-14/common/common.go
  internal/workspace/2024-05-14/gen.go
  internal/workspace/2024-05-14/links/links.config.yaml
  internal/workspace/2024-05-14/links/links.go
  internal/workspace/2024-05-14/mocks/workspace.go
  internal/workspace/2024-05-14/pacts/code-client-go-workspace-service.json
  internal/workspace/2024-05-14/parameters/content-type.config.yaml
  internal/workspace/2024-05-14/parameters/content-type.go
  internal/workspace/2024-05-14/parameters/orgs.config.yaml
  internal/workspace/2024-05-14/parameters/orgs.go
  internal/workspace/2024-05-14/parameters/request-id.config.yaml
  internal/workspace/2024-05-14/parameters/request-id.go
  internal/workspace/2024-05-14/parameters/user-agent.config.yaml
  internal/workspace/2024-05-14/parameters/user-agent.go
  internal/workspace/2024-05-14/spec.config.yaml
  internal/workspace/2024-05-14/workspace.go
  internal/workspace/2024-05-14/workspaces/workspaces.config.yaml
  internal/workspace/2024-05-14/workspaces/workspaces.go
  scan_smoke_test.go
Labels: ignore-for-release

#81 fix: AI explain request body
  llm/api_client.go
  llm/api_client_test.go
  llm/types.go
Labels: fix

#83 feat: accept a target_reference value and pass it to the test request [OI-788]
  internal/analysis/analysis.go
  internal/api/test/2024-12-21/helper.go
Labels: feature

#84 fix: update interface to include target reference param
  scan.go
Labels: fix

#80 chore: add basic test for analysis
  internal/analysis/analysis_test.go
  internal/api/test/2024-12-21/helper.go
Labels: ignore-for-release

#85 fix: encode diffs sent to AI Explain API endpoint [IDE-1084]
  llm/api_client.go
  llm/api_client_test.go
Labels: fix
