Repository snyk/code-client-go, pull requests merged in 2025-02, with the labels that each got.

#72 chore: extend fingerprints with new v1 fingerprints
  sarif/sarif_types.go
Labels: ignore-for-release

#73 fix: Add missing error nil check to log msg
  internal/analysis/analysis.go
Labels: fix

#74 feat: new LLM binding
  http/http.go
  llm/api_client.go
  llm/api_client_test.go
  llm/binding.go
  llm/binding_smoke_test.go
  llm/binding_test.go
  llm/options.go
  llm/types.go
  observability/traceid.go
Labels: feature

#77 feat: Add support for stateful tests
  go.mod
  go.sum
  internal/analysis/analysis.go
  internal/analysis/analysis_test.go
  internal/analysis/mocks/analysis.go
  internal/api/test/2024-12-21/helper.go
  scan.go
  scan/resultmetadata.go
  scan/target.go
  scan_test.go
Labels: feature

#78 feat: updated AI Explain API interface for new API definition [IDE-954]
  go.mod
  llm/api_client.go
  llm/api_client_test.go
  llm/binding.go
  llm/binding_test.go
  llm/types.go
Labels: feature
